---
title: 'RMarkdown:  In Class Assignment'
author: "Brenda Luis"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
  ## Everything above this is R code that we need to make the file run! We'll discuss it next class.
```


Reminder: We learned how to do these things in class today, but there is a "Markdown Help" page available in RStudio (and lots of help if you google). 


# In-class Activity, Markdown

**Do not skip reading this line** Create a new section at the end of this file with the title "Your work here", and beneath it, do the following 3 things. To turn this in, make sure you've committed and pushed, and turn in the link to this repository to the assignment on Blackboard.  

1. Make a subsection called Wise words. Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called My semester. Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

- A _subsubheading_ with the name of the artist or author;    
- An example of their writing or lyrics (formatted in a *block of text*);   
- A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. The knitting will produce an html file, which you will also need to stage/commit/push once it exists! 

**Once you're done, remember to commit the changes and push the repo back to your assignment on GitHub!**

# Your work here
## Wise words 
> "Losing a rock is better than never having a rock" - Esquie

[Learn about Esquie here](https://clair-obscur.fandom.com/wiki/Esquie)
 
## My semester

|Course number | Course Title | Instructor|
|:-------------|:-------------|:----------|
**DATA 2401**    | *Data Science 1* | Dr. Katherine Shoemaker
**CS 4304**        | *Programming Language Concepts* | Dr. Emre Yilmaz
**CS 4395**        | *Senior Project* | Dr. Azadeh Izadi

## I recommend 

#### D4VD (David Anthony Burke)

Example Lyrics: One More Dance

[Verse 1]
The heavier the rain\
The heavier the snow\
The heavier the weight\
After watching you go\
The smile on your face\
As the music starts to play\ 
To empty your brain, oh\
A form of escape, oh\
\
[Chorus]\
Dance with your eyes wide shut\
Forty degrees 'round us\
Holding you closer than before\
The only way I'm letting you go\ 
Is if I can't see my hands\
If my heart beats one less\
Faster than it's ever before\
All that I ask of you is one more dance\


**Top Songs: **

* Here With Me 
* One More Dance 
* Friend Again
* Romantic Homicide 
* Crashing (with Kali Uchis)
